const members = [
    {
        id: 1,
        name:  "Oh Se-hun",
        img: "https://upload.wikimedia.org/wikipedia/commons/4/46/Oh_Se-hun_at_Rimowa_Essential_Poly_Color_Collection_Launch_on_July_5%2C_2019.png",
        instruments: "Vocals",
        age: "27",
        height: "1.83",
        netWorth: 7,
        donation: 8

    },
    {
        id: 2,
        name:  "Chen",
        img: "https://qph.fs.quoracdn.net/main-qimg-e24c1666420133b98bd6d70c7d7653a5",
        instruments: "Main Vocals",
        age: "29",
        height: "1.72",
        netWorth: 10,
        donation: 9

    },
    {
        id: 3,
        name:  "Lay Zhang",
        img: "https://i.mydramalist.com/k615O_5f.jpg",
        instruments: "Vocals",
        age: "29",
        height: "1.77",
        netWorth: 8,
        donation: 5

    },
    {
        id: 4,
        name:  "Park Chan-yeol",
        img: "https://i.mydramalist.com/EoQrl_5f.jpg",
        instruments: "Rapper, Song writter",
        age: "28",
        height: "1.85",
        netWorth: 8,
        donation: 7

    },
    {
        id: 5,
        name:  "Kai",
        img: "https://i.pinimg.com/originals/48/d0/b3/48d0b3008bf41b226226a4283f1441e6.jpg",
        instruments: "Vocals",
        age: "27",
        height: "1.82",
        netWorth: 7,
        donation: 3

    },
    {
        id: 6,
        name:  "Byun Baek-hyun",
        img: "https://static.wikia.nocookie.net/thelostplanet/images/e/ea/Baekhyun_%28Don%27t_Fight_The_Feeling%29_4.png/revision/latest?cb=20210527015045",
        instruments: "Main Vocals",
        age: "29",
        height: "1.74",
        netWorth: 15,
        donation: 10

    },
    {
        id: 7,
        name:  "Do Kyung-soo",
        img: "https://i.mydramalist.com/43e46f.jpg",
        instruments: "Main Vocals",
        age: "28",
        height: "1.73",
        netWorth: 10,
        donation: 9

    },
    {
        id: 8,
        name:  "Xiumin",
        img: "https://i.pinimg.com/originals/fe/47/7f/fe477ff7146315d6cc893ef7751dd65f.jpg",
        instruments: "Lead Vocalist",
        age: "31",
        height: "1.73",
        netWorth: 7,
        donation: 3

    },
    {
        id: 9,
        name:  "Suho",
        img: "https://6.viki.io/image/d6e865ce4fe24cff99b298097bf032e4.jpeg?s=900x600&e=t",
        instruments: "Lead Vocalist",
        age: "30",
        height: "1.73m",
        netWorth: 10,
        donation: 5

    }
    
    
]